options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _NAME: "chartlib-http"

steps:
  # Build the Docker image.
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/${_NAME}:latest", "."]

  # Push the Docker image to the repository.
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_NAME}:latest"]

  # Deploy the Cloud Run service.
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_NAME}",
        "--image",
        "gcr.io/$PROJECT_ID/${_NAME}:latest",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
      ]

images:
  - "gcr.io/$PROJECT_ID/${_NAME}:latest"
