name: Merge
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        with:
          version: 8.10.2

      - name: Install dependencies
        run: pnpm install

      - name: Get package version
        id: get_package_version
        run: |
          echo "::set-output name=version::$(node -p 'require(`./package.json`).version')"

      - id: gcloud_auth
        name: gCloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy
        id: deploy
        run: gcloud builds submit

      - name: Create release
        run: |
          gh release create v$VERSION --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_package_version.outputs.version }}
