name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version (e.g. "1.0.0")
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          ref: main
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        with:
          version: 8.10.2

      - name: Install dependencies
        run: pnpm install

      - name: Configure git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Pull main
        run: git pull origin main

      - name: Create release branch
        run: |
          RELEASE_BRANCH="release/${{ inputs.version }}"
          git checkout -b "$RELEASE_BRANCH"
        env:
          VERSION: ${{ inputs.version }}

      - name: Push release branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: release/${{ inputs.version }}

      - name: Run build
        run: pnpm build

      - name: Bump version
        run: pnpm version $VERSION --no-commit-hooks --no-git-tag-version --no-workspaces-update
        env:
          VERSION: ${{ inputs.version }}

      - name: Commit updated build files
        run: |
          git add dist/*
          git add package.json
          git commit -m "🤖 build v$VERSION"
        env:
          VERSION: ${{ inputs.version }}

      - name: Bump version dependency for http
        run: |
          cd http/
          pnpm i
          pnpm add github:luabase/definite-chartlib#v$VERSION
          pnpm add github:luabase/definite-chartlib#v$VERSION
          pnpm version $VERSION --no-commit-hooks --no-git-tag-version --no-workspaces-update
          cd ..
        env:
          VERSION: ${{ inputs.version }}

      - id: gcloud_auth
        name: gCloud Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Deploy
        id: deploy
        run: gcloud builds submit

      - name: Commit updated http files
        run: |
          git add http/package.json
          git add http/pnpm-lock.yaml
          git commit -m "🤖 http deploy v$VERSION"
        env:
          VERSION: ${{ inputs.version }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.ref }}

      - name: Open Pull Request
        id: pr
        run: |
          PR_URL=$(gh pr create --base main --head release/${{ inputs.version }} --title "Release ${{ inputs.version }}" --body "Release pull request for version ${{ inputs.version }}" --json url)
          echo "::set-output name=url::$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          VERSION: ${{ inputs.version }}

      - name: Merge Pull Request
        run: |
          PR_NUMBER=$(basename ${{ steps.pr.outputs.url }})
          gh pr merge $PR_NUMBER --squash --admin
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Create release
        run: |
          gh release create v$VERSION --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          VERSION: ${{ inputs.version }}
